apiVersion: v1
kind: Service
metadata:
  name: redirection
  namespace: pc
spec:
  ports:
  - port: 80
    protocol: TCP
    name: port-5000
    targetPort: 5000
  selector:
    run: redirection
  type: ClusterIP
